os:
- linux
sudo: false
language: android
android:
  components:
  - build-tools-27.0.2
  - android 27
  licenses:
  - 'android-sdk-license-.+'

before_install:
- yes | sdkmanager "platforms;android-27"
install:
- gem install bundler
- bundle install
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
    - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
    - lib32stdc++6
    - fonts-droid
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- ./flutter/bin/flutter doctor
script:
- ./flutter/bin/flutter test --coverage
after_success:
# - coveralls-lcov coverage/lcov.info
#- ./flutter/bin/flutter packages get
#- ./flutter/bin/flutter packages pub run flutter_launcher_icons:main
- ./flutter/bin/flutter build apk --release
#- echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > ./android/secret.json
#- cd android
#- wc -l secret.json
#- fastlane alpha
cache:
  directories:
  - $HOME/.pub-cache