targets:
  $default:
    builders:
      json_serializable|json_serializable:
        generate_for:
          - "**/*models.dart"
      freezed|freezed:
        generate_for:
          - "**/*models.dart"
          - "**/*entities.dart"
