# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :internal do
    android_set_version_code(
      gradle_file: 'app/build.gradle'
    )
    gradle(
      task: 'clean assembleRelease'
    )
    supply(
      track: 'internal',
      apk: '../build/app/outputs/apk/release/app-release.apk'
    )
  end

  desc "Submit a new Alpha Build to the Play Store"
    lane :alpha do
      android_set_version_code(
        gradle_file: 'app/build.gradle'
      )

      upload_to_play_store(
          track: 'alpha',
          apk: '../build/app/outputs/apk/release/app-release.apk',
          json_key: 'secret.json',
          skip_upload_screenshots: true,
          skip_upload_images: true
      )
    end

  desc "Submit a new Beta Build to the Play Store"
  lane :beta do
    android_set_version_code(
      gradle_file: 'app/build.gradle'
    )

    upload_to_play_store(
        track: 'beta',
        apk: '../build/app/outputs/apk/release/app-release.apk',
        json_key: 'secret.json',
        skip_upload_screenshots: true,
        skip_upload_images: true
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "assembleRelease")
    android_set_version_code(
      gradle_file: 'app/build.gradle'
    )
    upload_to_play_store
  end
end
